### ISSUE TITLE
Bug: Boost button not there and restore boost doesn't add it.

### ISSUE THREAD

**Issue by funkymonkeymonk** [funkymonkeymonk/MarvelChampionsScripted#25]
There are no buttons for Boost cards underneath the Villain, anymore. There is a Boost button top left of the table, which says "Restore Boost", but it doesn't do anything for me.

**Comment by SwedeRacer** [comment]
It turns out that the boost button, like the 1-4 player buttons, is created on villains bag. Since button positions are relative to the item they are created on, these buttons got moved way out into space when I moved the villains bag. I repositioned them so that they show up where they're expected again.
