### ISSUE TITLE
Feature Request: Clearer description of what the buttons on the player mats do

### ISSUE THREAD

**Issue by funkymonkeymonk** [funkymonkeymonk/MarvelChampionsScripted#28]
I always disliked the naming of the buttons on the right side of the player mats (i.e. "I'm hit!", "Look out!"). They are non-descriptive and not intuitive. I think it would be much better to put what the buttons actually do in the Name (or at least Description) field (i.e. "Ready up!", "Discard random card", "Get face-down Encounter card", "Discard Encounter card").

**Comment by SwedeRacer** [comment]
I've updated the tooltips of the playmat buttons to make them clearer. I didn't want to add any text to the buttons themselves, since that would have taken more room on the mat (I did try to use emoji for the buttons, but TTS doesn't seem to support it). I also changed the "U" button (which I assume stood for "untap") to "R" for "ready).
