### ISSUE TITLE
Support a low/no code way of adding new modular encounters

### ISSUE THREAD

**Issue by funkymonkeymonk** [funkymonkeymonk/MarvelChampionsScripted#9]
Most modular encounters require no custom scripting. The goal of this is to make it trivial to add a new modular encounter to reduce the time from scanned to released.

**Comment by SwedeRacer** [comment]
The modular set system has been completely overhauled so that it no longer requires each set to be in its own bag. Now, we only need to add a new set to the Modular Sets Bag (after confirming that the deck's name is "[set name] Modular Set" and turning the deck upside-down) and save the mod. On load, a button for the new set will be added to the layout, and clicking the button will set the deck's scale and add it to the encounter deck.
